export interface Area {
  name: string;
  region: string;
  popular: boolean;
}

export const mumbaiAreas: Area[] = [
  { name: "Andheri East", region: "Western Suburbs", popular: true },
  { name: "Andheri West", region: "Western Suburbs", popular: true },
  { name: "Bandra East", region: "Western Suburbs", popular: true },
  { name: "Bandra West", region: "Western Suburbs", popular: true },
  { name: "Borivali East", region: "Western Suburbs", popular: true },
  { name: "Borivali West", region: "Western Suburbs", popular: true },
  { name: "Malad East", region: "Western Suburbs", popular: true },
  { name: "Malad West", region: "Western Suburbs", popular: true },
  { name: "Goregaon East", region: "Western Suburbs", popular: true },
  { name: "Goregaon West", region: "Western Suburbs", popular: true },
  { name: "Kandivali East", region: "Western Suburbs", popular: false },
  { name: "Kandivali West", region: "Western Suburbs", popular: false },
  { name: "Jogeshwari East", region: "Western Suburbs", popular: false },
  { name: "Jogeshwari West", region: "Western Suburbs", popular: false },
  { name: "Vile Parle East", region: "Western Suburbs", popular: false },
  { name: "Vile Parle West", region: "Western Suburbs", popular: false },
  { name: "Santacruz East", region: "Western Suburbs", popular: false },
  { name: "Santacruz West", region: "Western Suburbs", popular: false },
  { name: "Juhu", region: "Western Suburbs", popular: true },
  { name: "Versova", region: "Western Suburbs", popular: false },
  { name: "Lokhandwala", region: "Western Suburbs", popular: false },
  { name: "Oshiwara", region: "Western Suburbs", popular: false },
  { name: "Khar", region: "Western Suburbs", popular: false },
  { name: "Dahisar", region: "Western Suburbs", popular: false },
  { name: "Dahisar East", region: "Western Suburbs", popular: false },
  { name: "DN Nagar", region: "Western Suburbs", popular: false },
  { name: "Four Bungalows", region: "Western Suburbs", popular: false },
  { name: "Marol", region: "Western Suburbs", popular: false },
  { name: "MIDC Andheri", region: "Western Suburbs", popular: false },
  { name: "SEEPZ", region: "Western Suburbs", popular: false },

  { name: "Thane West", region: "Thane", popular: true },
  { name: "Thane East", region: "Thane", popular: true },
  { name: "Mulund East", region: "Thane", popular: true },
  { name: "Mulund West", region: "Thane", popular: true },
  { name: "Bhandup East", region: "Thane", popular: false },
  { name: "Bhandup West", region: "Thane", popular: false },
  { name: "Ghodbunder Road", region: "Thane", popular: true },
  { name: "Kalyan East", region: "Thane", popular: true },
  { name: "Kalyan West", region: "Thane", popular: true },
  { name: "Dombivli East", region: "Thane", popular: true },
  { name: "Dombivli West", region: "Thane", popular: true },
  { name: "Bhiwandi", region: "Thane", popular: false },
  { name: "Ulhasnagar", region: "Thane", popular: false },
  { name: "Majiwada", region: "Thane", popular: false },
  { name: "Manpada", region: "Thane", popular: false },
  { name: "Hiranandani Estate", region: "Thane", popular: false },
  { name: "Vartak Nagar", region: "Thane", popular: false },
  { name: "Wagle Estate", region: "Thane", popular: false },
  { name: "Naupada", region: "Thane", popular: false },
  { name: "Kopri", region: "Thane", popular: false },
  { name: "Vasant Vihar Thane", region: "Thane", popular: false },

  { name: "Kurla East", region: "Central Suburbs", popular: true },
  { name: "Kurla West", region: "Central Suburbs", popular: true },
  { name: "Ghatkopar East", region: "Central Suburbs", popular: true },
  { name: "Ghatkopar West", region: "Central Suburbs", popular: true },
  { name: "Vikhroli East", region: "Central Suburbs", popular: false },
  { name: "Vikhroli West", region: "Central Suburbs", popular: false },
  { name: "Powai", region: "Central Suburbs", popular: true },
  { name: "Chembur", region: "Central Suburbs", popular: true },
  { name: "Sion", region: "Central Suburbs", popular: false },
  { name: "Dadar East", region: "Central Suburbs", popular: true },
  { name: "Dadar West", region: "Central Suburbs", popular: true },
  { name: "Wadala", region: "Central Suburbs", popular: false },
  { name: "Matunga", region: "Central Suburbs", popular: false },
  { name: "King Circle", region: "Central Suburbs", popular: false },
  { name: "Parel", region: "Central Suburbs", popular: false },
  { name: "Byculla", region: "Central Suburbs", popular: false },
  { name: "Vidyavihar", region: "Central Suburbs", popular: false },
  { name: "Kanjurmarg", region: "Central Suburbs", popular: false },
  { name: "Nahur", region: "Central Suburbs", popular: false },
  { name: "Govandi", region: "Central Suburbs", popular: false },
  { name: "Mankhurd", region: "Central Suburbs", popular: false },
  { name: "Tilak Nagar", region: "Central Suburbs", popular: false },
  { name: "Chunabhatti", region: "Central Suburbs", popular: false },
  { name: "GTB Nagar", region: "Central Suburbs", popular: false },

  { name: "Colaba", region: "South Mumbai", popular: true },
  { name: "Churchgate", region: "South Mumbai", popular: false },
  { name: "Fort", region: "South Mumbai", popular: false },
  { name: "Marine Lines", region: "South Mumbai", popular: false },
  { name: "Marine Drive", region: "South Mumbai", popular: true },
  { name: "Worli", region: "South Mumbai", popular: true },
  { name: "Lower Parel", region: "South Mumbai", popular: true },
  { name: "Prabhadevi", region: "South Mumbai", popular: false },
  { name: "Mahalaxmi", region: "South Mumbai", popular: false },
  { name: "Nariman Point", region: "South Mumbai", popular: true },
  { name: "Cuffe Parade", region: "South Mumbai", popular: false },
  { name: "Malabar Hill", region: "South Mumbai", popular: false },
  { name: "Girgaon", region: "South Mumbai", popular: false },
  { name: "Grant Road", region: "South Mumbai", popular: false },
  { name: "Tardeo", region: "South Mumbai", popular: false },
  { name: "Breach Candy", region: "South Mumbai", popular: false },
  { name: "Pedder Road", region: "South Mumbai", popular: false },
  { name: "Walkeshwar", region: "South Mumbai", popular: false },
  { name: "Kemps Corner", region: "South Mumbai", popular: false },
  { name: "Opera House", region: "South Mumbai", popular: false },
  { name: "Charni Road", region: "South Mumbai", popular: false },
  { name: "Mumbai Central", region: "South Mumbai", popular: false },
  { name: "Jacob Circle", region: "South Mumbai", popular: false },

  { name: "Navi Mumbai", region: "Navi Mumbai", popular: true },
  { name: "Vashi", region: "Navi Mumbai", popular: true },
  { name: "Nerul", region: "Navi Mumbai", popular: true },
  { name: "Belapur", region: "Navi Mumbai", popular: true },
  { name: "Panvel", region: "Navi Mumbai", popular: true },
  { name: "Kharghar", region: "Navi Mumbai", popular: true },
  { name: "Airoli", region: "Navi Mumbai", popular: false },
  { name: "Sanpada", region: "Navi Mumbai", popular: false },
  { name: "Kopar Khairane", region: "Navi Mumbai", popular: false },
  { name: "Ghansoli", region: "Navi Mumbai", popular: false },
  { name: "Turbhe", region: "Navi Mumbai", popular: false },
  { name: "Juinagar", region: "Navi Mumbai", popular: false },
  { name: "Seawoods", region: "Navi Mumbai", popular: true },
  { name: "Ulwe", region: "Navi Mumbai", popular: false },
  { name: "Kamothe", region: "Navi Mumbai", popular: false },
  { name: "Taloja", region: "Navi Mumbai", popular: false },
  { name: "Kalamboli", region: "Navi Mumbai", popular: false },
  { name: "Khandeshwar", region: "Navi Mumbai", popular: false },
  { name: "New Panvel", region: "Navi Mumbai", popular: false },
  { name: "CBD Belapur", region: "Navi Mumbai", popular: false },

  { name: "Mira Road", region: "Extended Western", popular: true },
  { name: "Bhayandar East", region: "Extended Western", popular: true },
  { name: "Bhayandar West", region: "Extended Western", popular: true },
  { name: "Vasai East", region: "Extended Western", popular: true },
  { name: "Vasai West", region: "Extended Western", popular: true },
  { name: "Virar East", region: "Extended Western", popular: true },
  { name: "Virar West", region: "Extended Western", popular: true },
  { name: "Nalasopara East", region: "Extended Western", popular: false },
  { name: "Nalasopara West", region: "Extended Western", popular: false },
  { name: "Palghar", region: "Extended Western", popular: false },
  { name: "Naigaon", region: "Extended Western", popular: false },
  { name: "Nallasopara", region: "Extended Western", popular: false },

  { name: "Badlapur East", region: "Extended Eastern", popular: false },
  { name: "Badlapur West", region: "Extended Eastern", popular: false },
  { name: "Ambernath East", region: "Extended Eastern", popular: false },
  { name: "Ambernath West", region: "Extended Eastern", popular: false },
  { name: "Karjat", region: "Extended Eastern", popular: false },
  { name: "Titwala", region: "Extended Eastern", popular: false },
  { name: "Shahad", region: "Extended Eastern", popular: false },
  { name: "Vitthalwadi", region: "Extended Eastern", popular: false },
  { name: "Asangaon", region: "Extended Eastern", popular: false },
  { name: "Kasara", region: "Extended Eastern", popular: false },
];

export const regions = ["Western Suburbs", "Central Suburbs", "South Mumbai", "Thane", "Navi Mumbai", "Extended Western", "Extended Eastern"];

export function getAreasByRegion(region: string): Area[] {
  return mumbaiAreas.filter((a) => a.region === region);
}
