import svcMotherboardImg from "@assets/svc-motherboard.png";
import svcBackglassImg from "@assets/svc-backglass.png";
import svcBackpanelImg from "@assets/svc-backpanel.png";
import svcDiagnosisImg from "@assets/svc-diagnosis.png";

export interface Brand {
  name: string;
  slug: string;
  logo: string;
  heroImage: string;
  tagline: string;
  description: string;
  popularModels: string[];
  problems: { name: string; description: string }[];
}

export const allBrands: Brand[] = [
  {
    name: "Apple",
    slug: "apple",
    logo: "/images/logos/apple.png",
    heroImage: "/images/brand-apple.png",
    tagline: "Expert Apple iPhone & iPad Repair",
    description: "Certified repair for all Apple devices including iPhone, iPad, MacBook & Apple Watch. We use genuine quality parts with 3 to 6 months warranty.",
    popularModels: ["iPhone 16 Pro Max", "iPhone 16 Pro", "iPhone 16", "iPhone 15 Pro Max", "iPhone 15", "iPhone 14", "iPhone 13", "iPhone SE", "iPad Pro", "iPad Air"],
    problems: [
      { name: "Screen Replacement", description: "Original quality OLED/LCD display replacement" },
      { name: "Battery Replacement", description: "Genuine battery for improved performance" },
      { name: "Charging Port Repair", description: "Lightning/USB-C port repair or replacement" },
      { name: "Camera Repair", description: "Front/rear camera module replacement" },
      { name: "Water Damage", description: "Complete water damage treatment & repair" },
      { name: "Software Issue", description: "iOS update, restore, and troubleshooting" },
    ],
  },
  {
    name: "Xiaomi (Mi)",
    slug: "xiaomi",
    logo: "/images/logos/xiaomi.png",
    heroImage: "/images/brand-xiaomi.png",
    tagline: "Professional Xiaomi & Redmi Repair",
    description: "Expert repair for all Xiaomi, Redmi, and POCO devices. Quick doorstep service with genuine parts and warranty.",
    popularModels: ["Xiaomi 14 Ultra", "Xiaomi 14", "Redmi Note 13 Pro+", "Redmi Note 13", "Redmi 13C", "POCO F6 Pro", "POCO X6 Pro", "Xiaomi Pad 6"],
    problems: [
      { name: "Screen Replacement", description: "AMOLED/IPS display replacement" },
      { name: "Battery Replacement", description: "Genuine battery replacement" },
      { name: "Charging Port Repair", description: "USB-C port repair" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Water Damage", description: "Water damage treatment" },
      { name: "Software Issue", description: "MIUI troubleshooting & update" },
    ],
  },
  {
    name: "Samsung",
    slug: "samsung",
    logo: "/images/logos/samsung.png",
    heroImage: "/images/brand-samsung.png",
    tagline: "Samsung Galaxy Expert Repair Service",
    description: "Professional repair for all Samsung Galaxy phones, tablets, and watches. AMOLED screen specialists with doorstep service.",
    popularModels: ["Galaxy S24 Ultra", "Galaxy S24+", "Galaxy S24", "Galaxy S23", "Galaxy A55", "Galaxy A35", "Galaxy A15", "Galaxy Z Fold 5", "Galaxy Z Flip 5", "Galaxy Tab S9"],
    problems: [
      { name: "Screen Replacement", description: "Super AMOLED display replacement" },
      { name: "Battery Replacement", description: "Genuine battery replacement" },
      { name: "Charging Port Repair", description: "USB-C port repair" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Water Damage", description: "Water damage treatment" },
      { name: "Software Issue", description: "One UI troubleshooting" },
    ],
  },
  {
    name: "Vivo",
    slug: "vivo",
    logo: "/images/logos/vivo.png",
    heroImage: "/images/brand-apple.png",
    tagline: "Vivo Phone Repair Specialists",
    description: "Quick and affordable Vivo phone repair at your doorstep. All models covered with genuine parts.",
    popularModels: ["Vivo X100 Pro", "Vivo X100", "Vivo V30 Pro", "Vivo V30", "Vivo T3 Pro", "Vivo Y200", "Vivo Y100"],
    problems: [
      { name: "Screen Replacement", description: "AMOLED/IPS display replacement" },
      { name: "Battery Replacement", description: "Battery replacement" },
      { name: "Charging Port Repair", description: "Charging port fix" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Water Damage", description: "Water damage repair" },
      { name: "Software Issue", description: "Funtouch OS troubleshooting" },
    ],
  },
  {
    name: "OnePlus",
    slug: "oneplus",
    logo: "/images/logos/oneplus.png",
    heroImage: "/images/brand-oneplus.png",
    tagline: "OnePlus Device Repair Experts",
    description: "Expert OnePlus repair service. We handle everything from screen replacements to motherboard issues.",
    popularModels: ["OnePlus 12", "OnePlus 12R", "OnePlus Nord 4", "OnePlus Nord CE4", "OnePlus 11", "OnePlus Open"],
    problems: [
      { name: "Screen Replacement", description: "Fluid AMOLED display replacement" },
      { name: "Battery Replacement", description: "Battery replacement with Warp Charge support" },
      { name: "Charging Port Repair", description: "USB-C port repair" },
      { name: "Camera Repair", description: "Hasselblad camera repair" },
      { name: "Water Damage", description: "Water damage treatment" },
      { name: "Software Issue", description: "OxygenOS troubleshooting" },
    ],
  },
  {
    name: "Oppo",
    slug: "oppo",
    logo: "/images/logos/oppo.png",
    heroImage: "/images/brand-samsung.png",
    tagline: "Oppo Phone Repair Service",
    description: "Professional Oppo repair at your doorstep. All Reno, F, and A series devices covered.",
    popularModels: ["Oppo Find X7 Ultra", "Oppo Reno 12 Pro", "Oppo Reno 12", "Oppo F27 Pro+", "Oppo A80", "Oppo A60"],
    problems: [
      { name: "Screen Replacement", description: "AMOLED/IPS display replacement" },
      { name: "Battery Replacement", description: "Battery replacement" },
      { name: "Charging Port Repair", description: "SuperVOOC port repair" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Water Damage", description: "Water damage treatment" },
      { name: "Software Issue", description: "ColorOS troubleshooting" },
    ],
  },
  {
    name: "Google Pixel",
    slug: "google",
    logo: "/images/logos/google.png",
    heroImage: "/images/brand-google.png",
    tagline: "Google Pixel Repair Service",
    description: "Specialized Google Pixel repair. Screen, battery, camera and more - all fixed at your doorstep.",
    popularModels: ["Pixel 9 Pro XL", "Pixel 9 Pro", "Pixel 9", "Pixel 8 Pro", "Pixel 8", "Pixel 8a", "Pixel 7a"],
    problems: [
      { name: "Screen Replacement", description: "OLED display replacement" },
      { name: "Battery Replacement", description: "Battery replacement" },
      { name: "Charging Port Repair", description: "USB-C port repair" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Water Damage", description: "Water damage treatment" },
      { name: "Software Issue", description: "Android troubleshooting" },
    ],
  },
  {
    name: "Realme",
    slug: "realme",
    logo: "/images/logos/realme.png",
    heroImage: "/images/brand-xiaomi.png",
    tagline: "Realme Phone Repair Experts",
    description: "Fast and affordable Realme repair service. GT, Narzo, and C series covered.",
    popularModels: ["Realme GT 6", "Realme GT Neo 5", "Realme 12 Pro+", "Realme Narzo 70 Pro", "Realme C67", "Realme 12"],
    problems: [
      { name: "Screen Replacement", description: "Display replacement" },
      { name: "Battery Replacement", description: "Battery replacement" },
      { name: "Charging Port Repair", description: "DART charge port repair" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Water Damage", description: "Water damage repair" },
      { name: "Software Issue", description: "Realme UI troubleshooting" },
    ],
  },
  {
    name: "Motorola",
    slug: "motorola",
    logo: "/images/logos/motorola.png",
    heroImage: "/images/brand-samsung.png",
    tagline: "Motorola Repair Specialists",
    description: "Expert Motorola repair for Edge, Razr, and G series. Doorstep service with warranty.",
    popularModels: ["Moto Edge 50 Pro", "Moto Edge 50 Ultra", "Moto Razr 50", "Moto G85", "Moto G64", "Moto G34"],
    problems: [
      { name: "Screen Replacement", description: "pOLED/IPS display replacement" },
      { name: "Battery Replacement", description: "Battery replacement" },
      { name: "Charging Port Repair", description: "TurboPower port repair" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Water Damage", description: "Water damage treatment" },
      { name: "Software Issue", description: "Stock Android troubleshooting" },
    ],
  },
  {
    name: "iQOO",
    slug: "iqoo",
    logo: "/images/logos/iqoo.png",
    heroImage: "/images/brand-apple.png",
    tagline: "iQOO Phone Repair Service",
    description: "Professional iQOO repair for all Neo and Z series phones. Quick turnaround.",
    popularModels: ["iQOO 12", "iQOO Neo 9 Pro", "iQOO Neo 7 Pro", "iQOO Z9", "iQOO Z7 Pro"],
    problems: [
      { name: "Screen Replacement", description: "AMOLED display replacement" },
      { name: "Battery Replacement", description: "Battery replacement" },
      { name: "Charging Port Repair", description: "FlashCharge port repair" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Water Damage", description: "Water damage treatment" },
      { name: "Software Issue", description: "Funtouch OS troubleshooting" },
    ],
  },
  {
    name: "POCO",
    slug: "poco",
    logo: "/images/logos/poco.png",
    heroImage: "/images/brand-xiaomi.png",
    tagline: "POCO Phone Repair Experts",
    description: "Fast repair for all POCO phones. F, X, M, and C series covered with genuine parts.",
    popularModels: ["POCO F6 Pro", "POCO F6", "POCO X6 Pro", "POCO X6", "POCO M6 Pro", "POCO C65"],
    problems: [
      { name: "Screen Replacement", description: "AMOLED/IPS display replacement" },
      { name: "Battery Replacement", description: "Battery replacement" },
      { name: "Charging Port Repair", description: "Turbo Charge port repair" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Water Damage", description: "Water damage treatment" },
      { name: "Software Issue", description: "MIUI/HyperOS troubleshooting" },
    ],
  },
  {
    name: "Tecno",
    slug: "tecno",
    logo: "/images/logos/tecno.png",
    heroImage: "/images/brand-samsung.png",
    tagline: "Tecno Phone Repair Service",
    description: "Affordable Tecno phone repair. Camon, Spark, and Pova series expert repair.",
    popularModels: ["Tecno Camon 30 Pro", "Tecno Camon 30", "Tecno Spark 20 Pro+", "Tecno Pova 6 Pro", "Tecno Pop 8"],
    problems: [
      { name: "Screen Replacement", description: "Display replacement" },
      { name: "Battery Replacement", description: "Battery replacement" },
      { name: "Charging Port Repair", description: "Charging port repair" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Water Damage", description: "Water damage treatment" },
      { name: "Software Issue", description: "HiOS troubleshooting" },
    ],
  },
  {
    name: "Nothing",
    slug: "nothing",
    logo: "/images/logos/nothing.png",
    heroImage: "/images/brand-oneplus.png",
    tagline: "Nothing Phone Repair Experts",
    description: "Specialized Nothing Phone repair including Glyph interface. Expert technicians.",
    popularModels: ["Nothing Phone (2a) Plus", "Nothing Phone (2a)", "Nothing Phone (2)", "Nothing Phone (1)"],
    problems: [
      { name: "Screen Replacement", description: "OLED display replacement" },
      { name: "Battery Replacement", description: "Battery replacement" },
      { name: "Charging Port Repair", description: "USB-C port repair" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Glyph Interface Repair", description: "Glyph LED panel repair" },
      { name: "Software Issue", description: "Nothing OS troubleshooting" },
    ],
  },
  {
    name: "Nokia",
    slug: "nokia",
    logo: "/images/logos/nokia.png",
    heroImage: "/images/brand-google.png",
    tagline: "Nokia Phone Repair Service",
    description: "Professional Nokia phone repair. All models covered with quality parts.",
    popularModels: ["Nokia G42 5G", "Nokia G310", "Nokia C32", "Nokia C22", "Nokia XR21"],
    problems: [
      { name: "Screen Replacement", description: "Display replacement" },
      { name: "Battery Replacement", description: "Battery replacement" },
      { name: "Charging Port Repair", description: "Charging port repair" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Water Damage", description: "Water damage treatment" },
      { name: "Software Issue", description: "Android troubleshooting" },
    ],
  },
  {
    name: "Honor",
    slug: "honor",
    logo: "/images/logos/honor.png",
    heroImage: "/images/brand-samsung.png",
    tagline: "Honor Phone Repair Experts",
    description: "Expert repair for Honor Magic and X series phones. Quick doorstep service.",
    popularModels: ["Honor Magic 6 Pro", "Honor Magic V2", "Honor 200 Pro", "Honor X9b", "Honor X7b"],
    problems: [
      { name: "Screen Replacement", description: "OLED display replacement" },
      { name: "Battery Replacement", description: "Battery replacement" },
      { name: "Charging Port Repair", description: "SuperCharge port repair" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Water Damage", description: "Water damage treatment" },
      { name: "Software Issue", description: "MagicOS troubleshooting" },
    ],
  },
  {
    name: "Asus",
    slug: "asus",
    logo: "/images/logos/asus.png",
    heroImage: "/images/brand-apple.png",
    tagline: "Asus Phone & Laptop Repair",
    description: "Specialized Asus repair for ROG Phone and ZenFone. Gaming phone experts.",
    popularModels: ["ROG Phone 8 Pro", "ROG Phone 8", "Zenfone 11 Ultra", "Zenfone 10"],
    problems: [
      { name: "Screen Replacement", description: "AMOLED display replacement" },
      { name: "Battery Replacement", description: "Battery replacement" },
      { name: "Charging Port Repair", description: "HyperCharge port repair" },
      { name: "Camera Repair", description: "Camera module replacement" },
      { name: "Water Damage", description: "Water damage treatment" },
      { name: "Software Issue", description: "ZenUI troubleshooting" },
    ],
  },
  {
    name: "Huawei",
    slug: "huawei",
    logo: "/images/logos/huawei.png",
    heroImage: "/images/brand-google.png",
    tagline: "Huawei Device Repair Service",
    description: "Professional Huawei phone and tablet repair. Mate and P series specialists.",
    popularModels: ["Huawei Mate 60 Pro", "Huawei P60 Pro", "Huawei Nova 12", "Huawei MatePad Pro"],
    problems: [
      { name: "Screen Replacement", description: "OLED display replacement" },
      { name: "Battery Replacement", description: "Battery replacement" },
      { name: "Charging Port Repair", description: "SuperCharge port repair" },
      { name: "Camera Repair", description: "Leica camera module replacement" },
      { name: "Water Damage", description: "Water damage treatment" },
      { name: "Software Issue", description: "HarmonyOS troubleshooting" },
    ],
  },
];

export function getBrandBySlug(slug: string): Brand | undefined {
  return allBrands.find((b) => b.slug === slug);
}

export const serviceDetails = [
  {
    slug: "screen-replacement",
    name: "Screen Replacement",
    icon: "Monitor",
    heroImage: "/images/service-screen.png",
    description: "Professional screen replacement service for all devices. We use original quality OLED, AMOLED, and LCD displays to restore your device to perfect condition.",
    features: ["Original quality displays", "Same-day repair", "30-minute doorstep service", "3 to 6 months warranty", "All brands covered"],
    faq: [
      { q: "How long does screen replacement take?", a: "Most screen replacements are completed within 20-30 minutes at your doorstep." },
      { q: "Do you use original screens?", a: "We use OEM quality screens that match the original display quality and color accuracy." },
      { q: "Is there a warranty on screen replacement?", a: "Yes, all screen replacements come with a 3 to 6 months warranty covering defects." },
    ],
  },
  {
    slug: "battery-replacement",
    name: "Battery Replacement",
    icon: "Battery",
    heroImage: "/images/service-battery.png",
    description: "Genuine battery replacement service to restore your device's battery life. We use certified batteries that meet OEM specifications.",
    features: ["Genuine certified batteries", "Battery health check", "30-minute service", "3 to 6 months warranty", "All models supported"],
    faq: [
      { q: "How do I know if I need a battery replacement?", a: "If your battery drains quickly, device shuts down unexpectedly, or battery is swollen, it needs replacement." },
      { q: "Will battery replacement affect my data?", a: "No, battery replacement does not affect your data. All your files and apps remain intact." },
      { q: "How long does the new battery last?", a: "A new battery typically provides 1.5-2 years of optimal performance with normal usage." },
    ],
  },
  {
    slug: "charging-issues",
    name: "Charging Issues",
    icon: "Zap",
    heroImage: "/images/service-charging.png",
    description: "Fix all charging problems including loose ports, slow charging, and cable connectivity issues. Our technicians handle USB-C, Lightning, and wireless charging repairs.",
    features: ["Port cleaning & repair", "Fast charge restoration", "Cable testing", "Wireless charging fix", "Same-day service"],
    faq: [
      { q: "Why is my phone not charging?", a: "Common causes include dust in the port, damaged cable, worn-out port, or software issues." },
      { q: "Can you fix wireless charging issues?", a: "Yes, we repair wireless charging coils and receivers for supported devices." },
      { q: "How long does charging port repair take?", a: "Most charging port repairs are completed within 20-30 minutes." },
    ],
  },
  {
    slug: "software-problems",
    name: "Software Problems",
    icon: "Code",
    heroImage: "/images/service-software.png",
    description: "Complete software repair including OS reinstallation, virus removal, data recovery, and performance optimization.",
    features: ["OS reinstallation", "Virus & malware removal", "Data backup & recovery", "Performance optimization", "App troubleshooting"],
    faq: [
      { q: "Will I lose my data during software repair?", a: "We always backup your data before any software repair. In most cases, no data is lost." },
      { q: "Can you remove viruses from my phone?", a: "Yes, we remove all types of malware, adware, and viruses from your device." },
      { q: "My phone is very slow, can you fix it?", a: "Yes, we optimize your device's performance by clearing cache, removing unnecessary files, and updating software." },
    ],
  },
  {
    slug: "water-damage",
    name: "Water Damage Treatment",
    icon: "Droplets",
    heroImage: "/images/service-water.png",
    description: "Emergency water damage repair service. We clean and restore water-damaged devices using professional ultrasonic cleaning equipment.",
    features: ["Emergency response", "Ultrasonic cleaning", "Component-level repair", "Corrosion treatment", "Data recovery attempt"],
    faq: [
      { q: "What should I do if my phone falls in water?", a: "Turn it off immediately, don't charge it, and bring it to us as soon as possible for the best chance of recovery." },
      { q: "Can water-damaged phones be fully repaired?", a: "Many water-damaged phones can be fully restored. Success depends on how quickly you get it to us and the extent of damage." },
      { q: "How long does water damage repair take?", a: "Water damage treatment typically takes 1-2 hours including drying, cleaning, and testing." },
    ],
  },
  {
    slug: "camera-speaker-repair",
    name: "Camera & Speaker Repair",
    icon: "Camera",
    heroImage: "/images/service-camera.png",
    description: "Fix blurry cameras, broken microphones, and speaker issues. We replace camera modules, speaker units, and microphone assemblies.",
    features: ["Camera module replacement", "Speaker replacement", "Microphone repair", "Autofocus fix", "Lens cleaning"],
    faq: [
      { q: "Why is my camera blurry?", a: "Blurry cameras can be caused by a dirty lens, damaged lens glass, or a faulty camera module." },
      { q: "Can you fix low speaker volume?", a: "Yes, we clean or replace speaker units to restore full audio quality." },
      { q: "Do you repair front and back cameras?", a: "Yes, we repair both front-facing and rear camera modules for all devices." },
    ],
  },
  {
    slug: "motherboard-repairing",
    name: "Motherboard Repairing",
    icon: "Cpu",
    heroImage: svcMotherboardImg,
    description: "Expert motherboard-level repair for dead phones, restart loops, overheating, and no power issues. Our skilled technicians use micro-soldering techniques to fix complex motherboard faults.",
    features: ["Micro-soldering repair", "Dead phone recovery", "Restart loop fix", "Overheating solution", "Component-level diagnosis"],
    faq: [
      { q: "Can a dead phone motherboard be repaired?", a: "Yes, many dead phone issues are caused by specific component failures on the motherboard that can be repaired with micro-soldering." },
      { q: "How long does motherboard repair take?", a: "Motherboard repairs typically take 1-3 hours depending on the complexity of the issue." },
      { q: "Is motherboard repair worth it?", a: "In most cases, motherboard repair is significantly cheaper than buying a new phone and can fully restore your device." },
    ],
  },
  {
    slug: "iphone-back-glass",
    name: "iPhone Back Glass",
    icon: "Smartphone",
    heroImage: svcBackglassImg,
    description: "Professional iPhone back glass replacement service. We carefully remove the broken back glass and install a brand new OEM quality back panel with precision.",
    features: ["OEM quality glass", "Precision installation", "Wireless charging compatible", "Color matching", "30-minute service"],
    faq: [
      { q: "Can iPhone back glass be replaced?", a: "Yes, we replace back glass for all iPhone models from iPhone 8 onwards using professional techniques." },
      { q: "Will wireless charging still work after replacement?", a: "Yes, we use wireless charging compatible back glass panels to ensure full functionality." },
      { q: "How long does iPhone back glass replacement take?", a: "Back glass replacement is typically completed within 30-45 minutes at your doorstep." },
    ],
  },
  {
    slug: "android-back-panel",
    name: "Android Back Panel",
    icon: "Tablet",
    heroImage: svcBackpanelImg,
    description: "Replace your cracked or damaged Android back panel with a brand new OEM quality replacement. We cover Samsung, OnePlus, Xiaomi, Vivo, Oppo and all major brands.",
    features: ["All Android brands", "OEM quality panels", "Color matching available", "Quick installation", "3 to 6 months warranty"],
    faq: [
      { q: "Which Android brands do you cover for back panel replacement?", a: "We cover Samsung, OnePlus, Xiaomi, Vivo, Oppo, Realme, and all other major Android brands." },
      { q: "How long does Android back panel replacement take?", a: "Most back panel replacements are completed within 20-30 minutes." },
      { q: "Do you have all color options available?", a: "We stock popular colors for most models. For rare colors, we can arrange them within 1-2 days." },
    ],
  },
  {
    slug: "diagnosis",
    name: "Diagnosis",
    icon: "Search",
    heroImage: svcDiagnosisImg,
    description: "Not sure what's wrong with your device? Our expert technicians will thoroughly diagnose your device and identify the exact issue. If you proceed with the repair, diagnosis is completely free!",
    features: ["Complete device checkup", "Hardware testing", "Software analysis", "Free with repair", "Detailed report", "Expert recommendation"],
    faq: [
      { q: "Is there a charge for diagnosis?", a: "If you proceed with the repair after diagnosis, there is NO diagnosis charge. Diagnosis charges apply only if you choose not to get the device repaired." },
      { q: "How long does diagnosis take?", a: "A thorough device diagnosis typically takes 15-30 minutes depending on the issue." },
      { q: "What does the diagnosis include?", a: "Our diagnosis includes complete hardware testing, software analysis, battery health check, and a detailed report of all issues found." },
    ],
  },
];

export function getServiceBySlug(slug: string) {
  return serviceDetails.find((s) => s.slug === slug);
}
